var linkedCouncilsIA11 = [
	{lc: "Banking & Capital Markets", linkCount: 81, rcs: ["Social Innovation", "International Legal System", "North America", "Trade", "Migration", "Space Security", "Employment & Social Protection", "China", "Emerging Multinationals", "Public & Institutional Investors", "Organized Crime", "Middle East & North Africa", "India", "Korea", "International Monetary System", "Poverty & Economic Development", "Innovation", "Private Fund Managers", "Mining & Metals", "Renewable Energy", "Fiscal Crises", "Insurance & Asset Management", "Real Estate", "South-East Asia", "Catastrophic Risks", "Values", "Systemic Financial Risk", "Geopolitical Risk", "Telecom", "Illicit Trade", "Africa", "Institutional Governance Systems"]},
	{lc: "Health", linkCount: 68, rcs: ["Social Innovation", "International Legal System", "Women's Empowerment", "Water Security", "Population Growth", "Japan", "Migration", "Humanitarian Assistance", "Consumer", "Chronic Diseases & Well-being", "Emerging Multinationals", "Health", "Competitiveness", "Benchmarking Progress", "India", "Ageing", "Innovation", "Fiscal Crises", "Design", "Emerging Technologies", "Intellectual Property System", "Terrorism", "Values", "Human Rights", "Urbanization", "Education", "Next Generation", "Food Security", "Telecom", "Africa", "Weapons of Mass Destruction"]},
	{lc: "Consumer", linkCount: 55, rcs: ["Social Innovation", "Water Security", "Population Growth", "Japan", "Migration", "Employment & Social Protection", "Consumer", "Chronic Diseases & Well-being", "Banking & Capital Markets", "Emerging Multinationals", "Benchmarking Progress", "Ecosystems & Biodiversity", "Automotive", "Korea", "Logistics & Supply Chain", "Ageing", "Innovation", "Design", "Media, Entertainment & Information", "Emerging Technologies", "Intellectual Property System", "South-East Asia", "Human Rights", "Education", "Next Generation", "Aviation, Travel & Tourism", "Food Security", "Telecom", "Illicit Trade"]},
	{lc: "Media, Entertainment & Information", linkCount: 53, rcs: ["Social Innovation", "Women's Empowerment", "Water Security", "Space Security", "Consumer", "Informed Societies", "Chronic Diseases & Well-being", "Health", "Competitiveness", "Benchmarking Progress", "Middle East & North Africa", "Future of Government", "Ocean Governance", "Ageing", "Skills & Talent Mobility", "Innovation", "Media, Entertainment & Information", "Intellectual Property System", "Terrorism", "Values", "Urbanization", "Education", "Next Generation", "Telecom", "Africa", "Weapons of Mass Destruction", "Institutional Governance Systems"]},
	{lc: "Renewable Energy", linkCount: 43, rcs: ["Social Innovation", "Water Security", "Conflict Prevention", "Europe & Central Asia", "Japan", "Competitiveness", "Future of Government", "Ocean Governance", "Ecosystems & Biodiversity", "Automotive", "Korea", "Climate Change", "Energy Security", "Logistics & Supply Chain", "Poverty & Economic Development", "Innovation", "Fragile States", "Design", "Emerging Technologies", "Values", "Geopolitical Risk", "Next Generation", "Aviation, Travel & Tourism", "Weapons of Mass Destruction"]},
	{lc: "NONE", linkCount: 24, rcs: ["Social Innovation", "International Legal System", "Women's Empowerment", "Water Security", "China", "Health", "Benchmarking Progress", "Ocean Governance", "India", "International Monetary System", "Skills & Talent Mobility", "Poverty & Economic Development", "Design", "Terrorism", "Values", "Human Rights", "Urbanization", "Next Generation", "Food Security", "Telecom", "Weapons of Mass Destruction", "Internet Security"]},
	{lc: "Public & Institutional Investors", linkCount: 36, rcs: ["Social Innovation", "International Legal System", "Employment & Social Protection", "Humanitarian Assistance", "Role of Business", "Health", "Future of Government", "India", "Skills & Talent Mobility", "Poverty & Economic Development", "Innovation", "Mining & Metals", "Insurance & Asset Management", "Real Estate", "Catastrophic Risks", "Human Rights", "Urbanization", "Aviation, Travel & Tourism", "Food Security", "Weapons of Mass Destruction", "Anti-Corruption", "Institutional Governance Systems"]},
	{lc: "Logistics & Supply Chain", linkCount: 33, rcs: ["Europe & Central Asia", "Trade", "Employment & Social Protection", "Humanitarian Assistance", "Consumer", "Health", "Competitiveness", "Latin America", "Ocean Governance", "Automotive", "Intellectual Property System", "Catastrophic Risks", "Geopolitical Risk", "Aviation, Travel & Tourism", "Food Security", "Illicit Trade", "Weapons of Mass Destruction"]},
	{lc: "Mining & Metals", linkCount: 18, rcs: ["International Legal System", "Water Security", "Trade", "China", "Organized Crime", "Middle East & North Africa", "Latin America", "Ocean Governance", "Poverty & Economic Development", "Fragile States", "Values", "Illicit Trade", "Weapons of Mass Destruction", "Anti-Corruption"]},
	{lc: "Telecom", linkCount: 26, rcs: ["North America", "Space Security", "Informed Societies", "Emerging Multinationals", "Health", "Future of Government", "Media, Entertainment & Information", "South-East Asia", "Human Rights", "Education", "Next Generation", "Africa", "Internet Security"]},
	{lc: "Aviation, Travel & Tourism", linkCount: 20, rcs: ["Women's Empowerment", "Migration", "Space Security", "Organized Crime", "Ecosystems & Biodiversity", "Climate Change", "Logistics & Supply Chain", "Skills & Talent Mobility", "Innovation", "Media, Entertainment & Information", "Terrorism", "Illicit Trade"]},
	{lc: "Insurance & Asset Management", linkCount: 12, rcs: ["Humanitarian Assistance", "Banking & Capital Markets", "Public & Institutional Investors", "Automotive", "Ageing", "Fragile States", "Insurance & Asset Management", "Catastrophic Risks", "Weapons of Mass Destruction"]},
	{lc: "Automotive", linkCount: 12, rcs: ["Japan", "Trade", "Future of Government", "India", "Climate Change", "Energy Security", "Mining & Metals", "Renewable Energy", "Design"]},
	{lc: "Private Fund Managers", linkCount: 4, rcs: ["Public & Institutional Investors", "Geopolitical Risk", "Mining & Metals", "Climate Change"]},
	{lc: "Real Estate", linkCount: 6, rcs: ["Urbanization", "Design", "Korea"]},
	{lc: "unknown", linkCount: 2, rcs: ["Skills & Talent Mobility", "International Legal System"]}
],
respondentCouncilsIA11 = [
	{rc: "Weapons of Mass Destruction", linkCount: 11, lcs: ["Health", "Public & Institutional Investors", "Logistics & Supply Chain", "NONE", "Mining & Metals", "Renewable Energy", "Media, Entertainment & Information", "Insurance & Asset Management"]},
	{rc: "Innovation", linkCount: 11, lcs: ["Consumer", "Banking & Capital Markets", "Health", "Public & Institutional Investors", "Renewable Energy", "Media, Entertainment & Information", "Aviation, Travel & Tourism"]},
	{rc: "Social Innovation", linkCount: 14, lcs: ["Consumer", "Banking & Capital Markets", "Health", "Public & Institutional Investors", "NONE", "Renewable Energy", "Media, Entertainment & Information"]},
	{rc: "Next Generation", linkCount: 11, lcs: ["Consumer", "Health", "NONE", "Renewable Energy", "Media, Entertainment & Information", "Telecom"]},
	{rc: "Values", linkCount: 10, lcs: ["Banking & Capital Markets", "Health", "NONE", "Mining & Metals", "Renewable Energy", "Media, Entertainment & Information"]},
	{rc: "Design", linkCount: 13, lcs: ["Consumer", "Health", "Automotive", "NONE", "Renewable Energy", "Real Estate"]},
	{rc: "Health", linkCount: 8, lcs: ["Health", "Public & Institutional Investors", "Logistics & Supply Chain", "NONE", "Media, Entertainment & Information", "Telecom"]},
	{rc: "Water Security", linkCount: 11, lcs: ["Consumer", "Health", "NONE", "Mining & Metals", "Renewable Energy", "Media, Entertainment & Information"]},
	{rc: "International Legal System", linkCount: 10, lcs: ["unknown", "Banking & Capital Markets", "Health", "Public & Institutional Investors", "NONE", "Mining & Metals"]},
	{rc: "Illicit Trade", linkCount: 12, lcs: ["Consumer", "Banking & Capital Markets", "Logistics & Supply Chain", "Mining & Metals", "Aviation, Travel & Tourism"]},
	{rc: "Telecom", linkCount: 6, lcs: ["Consumer", "Banking & Capital Markets", "Health", "NONE", "Media, Entertainment & Information"]},
	{rc: "Food Security", linkCount: 9, lcs: ["Consumer", "Health", "Public & Institutional Investors", "Logistics & Supply Chain", "NONE"]},
	{rc: "Urbanization", linkCount: 9, lcs: ["Health", "Public & Institutional Investors", "NONE", "Media, Entertainment & Information", "Real Estate"]},
	{rc: "Human Rights", linkCount: 5, lcs: ["Consumer", "Health", "Public & Institutional Investors", "NONE", "Telecom"]},
	{rc: "Poverty & Economic Development", linkCount: 9, lcs: ["Banking & Capital Markets", "Public & Institutional Investors", "NONE", "Mining & Metals", "Renewable Energy"]},
	{rc: "Skills & Talent Mobility", linkCount: 5, lcs: ["unknown", "Public & Institutional Investors", "NONE", "Media, Entertainment & Information", "Aviation, Travel & Tourism"]},
	{rc: "India", linkCount: 7, lcs: ["Banking & Capital Markets", "Health", "Public & Institutional Investors", "Automotive", "NONE"]},
	{rc: "Ocean Governance", linkCount: 8, lcs: ["Logistics & Supply Chain", "NONE", "Mining & Metals", "Renewable Energy", "Media, Entertainment & Information"]},
	{rc: "Future of Government", linkCount: 8, lcs: ["Public & Institutional Investors", "Automotive", "Renewable Energy", "Media, Entertainment & Information", "Telecom"]},
	{rc: "Africa", linkCount: 5, lcs: ["Telecom", "Banking & Capital Markets", "Health", "Media, Entertainment & Information"]},
	{rc: "Aviation, Travel & Tourism", linkCount: 8, lcs: ["Public & Institutional Investors", "Consumer", "Renewable Energy", "Logistics & Supply Chain"]},
	{rc: "Education", linkCount: 7, lcs: ["Telecom", "Health", "Consumer", "Media, Entertainment & Information"]},
	{rc: "Geopolitical Risk", linkCount: 6, lcs: ["Banking & Capital Markets", "Renewable Energy", "Private Fund Managers", "Logistics & Supply Chain"]},
	{rc: "Terrorism", linkCount: 8, lcs: ["Aviation, Travel & Tourism", "Health", "Media, Entertainment & Information", "NONE"]},
	{rc: "Catastrophic Risks", linkCount: 9, lcs: ["Public & Institutional Investors", "Banking & Capital Markets", "Insurance & Asset Management", "Logistics & Supply Chain"]},
	{rc: "Intellectual Property System", linkCount: 6, lcs: ["Health", "Consumer", "Media, Entertainment & Information", "Logistics & Supply Chain"]},
	{rc: "Media, Entertainment & Information", linkCount: 13, lcs: ["Aviation, Travel & Tourism", "Telecom", "Consumer", "Media, Entertainment & Information"]},
	{rc: "Mining & Metals", linkCount: 5, lcs: ["Automotive", "Public & Institutional Investors", "Banking & Capital Markets", "Private Fund Managers"]},
	{rc: "Ageing", linkCount: 10, lcs: ["Health", "Consumer", "Insurance & Asset Management", "Media, Entertainment & Information"]},
	{rc: "Climate Change", linkCount: 7, lcs: ["Automotive", "Aviation, Travel & Tourism", "Renewable Energy", "Private Fund Managers"]},
	{rc: "Korea", linkCount: 7, lcs: ["Banking & Capital Markets", "Consumer", "Real Estate", "Renewable Energy"]},
	{rc: "Automotive", linkCount: 6, lcs: ["Consumer", "Insurance & Asset Management", "Renewable Energy", "Logistics & Supply Chain"]},
	{rc: "Benchmarking Progress", linkCount: 8, lcs: ["Health", "Consumer", "Media, Entertainment & Information", "NONE"]},
	{rc: "Competitiveness", linkCount: 8, lcs: ["Health", "Media, Entertainment & Information", "Renewable Energy", "Logistics & Supply Chain"]},
	{rc: "Emerging Multinationals", linkCount: 6, lcs: ["Telecom", "Health", "Banking & Capital Markets", "Consumer"]},
	{rc: "Consumer", linkCount: 8, lcs: ["Health", "Consumer", "Media, Entertainment & Information", "Logistics & Supply Chain"]},
	{rc: "Humanitarian Assistance", linkCount: 7, lcs: ["Public & Institutional Investors", "Health", "Insurance & Asset Management", "Logistics & Supply Chain"]},
	{rc: "Employment & Social Protection", linkCount: 6, lcs: ["Public & Institutional Investors", "Banking & Capital Markets", "Consumer", "Logistics & Supply Chain"]},
	{rc: "Space Security", linkCount: 8, lcs: ["Aviation, Travel & Tourism", "Telecom", "Banking & Capital Markets", "Media, Entertainment & Information"]},
	{rc: "Migration", linkCount: 4, lcs: ["Aviation, Travel & Tourism", "Banking & Capital Markets", "Health", "Consumer"]},
	{rc: "Trade", linkCount: 7, lcs: ["Automotive", "Banking & Capital Markets", "Mining & Metals", "Logistics & Supply Chain"]},
	{rc: "Japan", linkCount: 8, lcs: ["Automotive", "Health", "Consumer", "Renewable Energy"]},
	{rc: "Women's Empowerment", linkCount: 5, lcs: ["Aviation, Travel & Tourism", "Health", "Media, Entertainment & Information", "NONE"]},
	{rc: "Institutional Governance Systems", linkCount: 4, lcs: ["Public & Institutional Investors", "Banking & Capital Markets", "Media, Entertainment & Information"]},
	{rc: "South-East Asia", linkCount: 5, lcs: ["Telecom", "Banking & Capital Markets", "Consumer"]},
	{rc: "Insurance & Asset Management", linkCount: 4, lcs: ["Public & Institutional Investors", "Banking & Capital Markets", "Insurance & Asset Management"]},
	{rc: "Emerging Technologies", linkCount: 7, lcs: ["Health", "Consumer", "Renewable Energy"]},
	{rc: "Fragile States", linkCount: 4, lcs: ["Insurance & Asset Management", "Renewable Energy", "Mining & Metals"]},
	{rc: "Logistics & Supply Chain", linkCount: 7, lcs: ["Aviation, Travel & Tourism", "Consumer", "Renewable Energy"]},
	{rc: "Ecosystems & Biodiversity", linkCount: 4, lcs: ["Aviation, Travel & Tourism", "Consumer", "Renewable Energy"]},
	{rc: "Middle East & North Africa", linkCount: 6, lcs: ["Banking & Capital Markets", "Media, Entertainment & Information", "Mining & Metals"]},
	{rc: "Organized Crime", linkCount: 7, lcs: ["Aviation, Travel & Tourism", "Banking & Capital Markets", "Mining & Metals"]},
	{rc: "Public & Institutional Investors", linkCount: 5, lcs: ["Banking & Capital Markets", "Insurance & Asset Management", "Private Fund Managers"]},
	{rc: "Chronic Diseases & Well-being", linkCount: 10, lcs: ["Health", "Consumer", "Media, Entertainment & Information"]},
	{rc: "China", linkCount: 6, lcs: ["Banking & Capital Markets", "Mining & Metals", "NONE"]},
	{rc: "Internet Security", linkCount: 4, lcs: ["Telecom", "NONE"]},
	{rc: "Anti-Corruption", linkCount: 5, lcs: ["Public & Institutional Investors", "Mining & Metals"]},
	{rc: "Real Estate", linkCount: 6, lcs: ["Public & Institutional Investors", "Banking & Capital Markets"]},
	{rc: "Fiscal Crises", linkCount: 4, lcs: ["Banking & Capital Markets", "Health"]},
	{rc: "Renewable Energy", linkCount: 2, lcs: ["Automotive", "Banking & Capital Markets"]},
	{rc: "Energy Security", linkCount: 6, lcs: ["Automotive", "Renewable Energy"]},
	{rc: "International Monetary System", linkCount: 6, lcs: ["Banking & Capital Markets", "NONE"]},
	{rc: "Latin America", linkCount: 2, lcs: ["Mining & Metals", "Logistics & Supply Chain"]},
	{rc: "Banking & Capital Markets", linkCount: 4, lcs: ["Consumer", "Insurance & Asset Management"]},
	{rc: "Informed Societies", linkCount: 10, lcs: ["Telecom", "Media, Entertainment & Information"]},
	{rc: "Population Growth", linkCount: 10, lcs: ["Health", "Consumer"]},
	{rc: "Europe & Central Asia", linkCount: 2, lcs: ["Renewable Energy", "Logistics & Supply Chain"]},
	{rc: "North America", linkCount: 4, lcs: ["Telecom", "Banking & Capital Markets"]},
	{rc: "Systemic Financial Risk", linkCount: 6, lcs: ["Banking & Capital Markets"]},
	{rc: "Private Fund Managers", linkCount: 1, lcs: ["Banking & Capital Markets"]},
	{rc: "Role of Business", linkCount: 2, lcs: ["Public & Institutional Investors"]},
	{rc: "Conflict Prevention", linkCount: 1, lcs: ["Renewable Energy"]}
],
linksIA11 = [
	{rci: 0, lci: 62, size: 2, strength: 0.18181818181818182, rc: "Weapons of Mass Destruction", lc: "Health"},
	{rci: 1, lci: 184, size: 2, strength: 0.18181818181818182, rc: "Weapons of Mass Destruction", lc: "Public & Institutional Investors"},
	{rci: 2, lci: 203, size: 1, strength: 0.09090909090909091, rc: "Weapons of Mass Destruction", lc: "Logistics & Supply Chain"},
	{rci: 3, lci: 163, size: 1, strength: 0.0, rc: "Weapons of Mass Destruction", lc: "NONE"},
	{rci: 4, lci: 216, size: 1, strength: 0.09090909090909091, rc: "Weapons of Mass Destruction", lc: "Mining & Metals"},
	{rci: 5, lci: 142, size: 1, strength: 0.09090909090909091, rc: "Weapons of Mass Destruction", lc: "Renewable Energy"},
	{rci: 6, lci: 117, size: 2, strength: 0.18181818181818182, rc: "Weapons of Mass Destruction", lc: "Media, Entertainment & Information"},
	{rci: 7, lci: 251, size: 1, strength: 0.09090909090909091, rc: "Weapons of Mass Destruction", lc: "Insurance & Asset Management"},
	{rci: 8, lci: 79, size: 1, strength: 0.09090909090909091, rc: "Innovation", lc: "Consumer"},
	{rci: 9, lci: 16, size: 4, strength: 0.36363636363636365, rc: "Innovation", lc: "Banking & Capital Markets"},
	{rci: 10, lci: 48, size: 1, strength: 0.09090909090909091, rc: "Innovation", lc: "Health"},
	{rci: 11, lci: 175, size: 1, strength: 0.09090909090909091, rc: "Innovation", lc: "Public & Institutional Investors"},
	{rci: 12, lci: 134, size: 1, strength: 0.09090909090909091, rc: "Innovation", lc: "Renewable Energy"},
	{rci: 13, lci: 107, size: 2, strength: 0.18181818181818182, rc: "Innovation", lc: "Media, Entertainment & Information"},
	{rci: 14, lci: 239, size: 1, strength: 0.09090909090909091, rc: "Innovation", lc: "Aviation, Travel & Tourism"},
	{rci: 15, lci: 63, size: 1, strength: 0.07142857142857142, rc: "Social Innovation", lc: "Consumer"},
	{rci: 16, lci: 0, size: 3, strength: 0.21428571428571427, rc: "Social Innovation", lc: "Banking & Capital Markets"},
	{rci: 17, lci: 32, size: 4, strength: 0.2857142857142857, rc: "Social Innovation", lc: "Health"},
	{rci: 18, lci: 165, size: 2, strength: 0.14285714285714285, rc: "Social Innovation", lc: "Public & Institutional Investors"},
	{rci: 19, lci: 143, size: 1, strength: 0.0, rc: "Social Innovation", lc: "NONE"},
	{rci: 20, lci: 119, size: 1, strength: 0.07142857142857142, rc: "Social Innovation", lc: "Renewable Energy"},
	{rci: 21, lci: 92, size: 2, strength: 0.14285714285714285, rc: "Social Innovation", lc: "Media, Entertainment & Information"},
	{rci: 22, lci: 87, size: 1, strength: 0.09090909090909091, rc: "Next Generation", lc: "Consumer"},
	{rci: 23, lci: 58, size: 4, strength: 0.36363636363636365, rc: "Next Generation", lc: "Health"},
	{rci: 24, lci: 160, size: 1, strength: 0.0, rc: "Next Generation", lc: "NONE"},
	{rci: 25, lci: 140, size: 1, strength: 0.09090909090909091, rc: "Next Generation", lc: "Renewable Energy"},
	{rci: 26, lci: 114, size: 3, strength: 0.2727272727272727, rc: "Next Generation", lc: "Media, Entertainment & Information"},
	{rci: 27, lci: 228, size: 1, strength: 0.09090909090909091, rc: "Next Generation", lc: "Telecom"},
	{rci: 28, lci: 25, size: 4, strength: 0.4, rc: "Values", lc: "Banking & Capital Markets"},
	{rci: 29, lci: 54, size: 1, strength: 0.1, rc: "Values", lc: "Health"},
	{rci: 30, lci: 157, size: 1, strength: 0.0, rc: "Values", lc: "NONE"},
	{rci: 31, lci: 214, size: 1, strength: 0.1, rc: "Values", lc: "Mining & Metals"},
	{rci: 32, lci: 138, size: 1, strength: 0.1, rc: "Values", lc: "Renewable Energy"},
	{rci: 33, lci: 111, size: 2, strength: 0.2, rc: "Values", lc: "Media, Entertainment & Information"},
	{rci: 34, lci: 80, size: 4, strength: 0.3076923076923077, rc: "Design", lc: "Consumer"},
	{rci: 35, lci: 50, size: 4, strength: 0.3076923076923077, rc: "Design", lc: "Health"},
	{rci: 36, lci: 260, size: 2, strength: 0.15384615384615385, rc: "Design", lc: "Automotive"},
	{rci: 37, lci: 155, size: 1, strength: 0.0, rc: "Design", lc: "NONE"},
	{rci: 38, lci: 136, size: 1, strength: 0.07692307692307693, rc: "Design", lc: "Renewable Energy"},
	{rci: 39, lci: 266, size: 1, strength: 0.07692307692307693, rc: "Design", lc: "Real Estate"},
	{rci: 40, lci: 43, size: 1, strength: 0.125, rc: "Health", lc: "Health"},
	{rci: 41, lci: 170, size: 1, strength: 0.125, rc: "Health", lc: "Public & Institutional Investors"},
	{rci: 42, lci: 192, size: 2, strength: 0.25, rc: "Health", lc: "Logistics & Supply Chain"},
	{rci: 43, lci: 148, size: 1, strength: 0.0, rc: "Health", lc: "NONE"},
	{rci: 44, lci: 99, size: 2, strength: 0.25, rc: "Health", lc: "Media, Entertainment & Information"},
	{rci: 45, lci: 222, size: 1, strength: 0.125, rc: "Health", lc: "Telecom"},
	{rci: 46, lci: 64, size: 5, strength: 0.45454545454545453, rc: "Water Security", lc: "Consumer"},
	{rci: 47, lci: 35, size: 1, strength: 0.09090909090909091, rc: "Water Security", lc: "Health"},
	{rci: 48, lci: 146, size: 1, strength: 0.0, rc: "Water Security", lc: "NONE"},
	{rci: 49, lci: 205, size: 1, strength: 0.09090909090909091, rc: "Water Security", lc: "Mining & Metals"},
	{rci: 50, lci: 120, size: 2, strength: 0.18181818181818182, rc: "Water Security", lc: "Renewable Energy"},
	{rci: 51, lci: 94, size: 1, strength: 0.09090909090909091, rc: "Water Security", lc: "Media, Entertainment & Information"},
	{rci: 52, lci: 269, size: 1, strength: 0.1, rc: "International Legal System", lc: "unknown"},
	{rci: 53, lci: 1, size: 3, strength: 0.3, rc: "International Legal System", lc: "Banking & Capital Markets"},
	{rci: 54, lci: 33, size: 1, strength: 0.1, rc: "International Legal System", lc: "Health"},
	{rci: 55, lci: 166, size: 1, strength: 0.1, rc: "International Legal System", lc: "Public & Institutional Investors"},
	{rci: 56, lci: 144, size: 3, strength: 0.0, rc: "International Legal System", lc: "NONE"},
	{rci: 57, lci: 204, size: 1, strength: 0.1, rc: "International Legal System", lc: "Mining & Metals"},
	{rci: 58, lci: 91, size: 2, strength: 0.16666666666666666, rc: "Illicit Trade", lc: "Consumer"},
	{rci: 59, lci: 29, size: 2, strength: 0.16666666666666666, rc: "Illicit Trade", lc: "Banking & Capital Markets"},
	{rci: 60, lci: 202, size: 5, strength: 0.4166666666666667, rc: "Illicit Trade", lc: "Logistics & Supply Chain"},
	{rci: 61, lci: 215, size: 1, strength: 0.08333333333333333, rc: "Illicit Trade", lc: "Mining & Metals"},
	{rci: 62, lci: 242, size: 2, strength: 0.16666666666666666, rc: "Illicit Trade", lc: "Aviation, Travel & Tourism"},
	{rci: 63, lci: 90, size: 1, strength: 0.16666666666666666, rc: "Telecom", lc: "Consumer"},
	{rci: 64, lci: 28, size: 1, strength: 0.16666666666666666, rc: "Telecom", lc: "Banking & Capital Markets"},
	{rci: 65, lci: 60, size: 2, strength: 0.3333333333333333, rc: "Telecom", lc: "Health"},
	{rci: 66, lci: 162, size: 1, strength: 0.0, rc: "Telecom", lc: "NONE"},
	{rci: 67, lci: 115, size: 1, strength: 0.16666666666666666, rc: "Telecom", lc: "Media, Entertainment & Information"},
	{rci: 68, lci: 89, size: 4, strength: 0.4444444444444444, rc: "Food Security", lc: "Consumer"},
	{rci: 69, lci: 59, size: 2, strength: 0.2222222222222222, rc: "Food Security", lc: "Health"},
	{rci: 70, lci: 183, size: 1, strength: 0.1111111111111111, rc: "Food Security", lc: "Public & Institutional Investors"},
	{rci: 71, lci: 201, size: 1, strength: 0.1111111111111111, rc: "Food Security", lc: "Logistics & Supply Chain"},
	{rci: 72, lci: 161, size: 1, strength: 0.0, rc: "Food Security", lc: "NONE"},
	{rci: 73, lci: 56, size: 1, strength: 0.1111111111111111, rc: "Urbanization", lc: "Health"},
	{rci: 74, lci: 181, size: 2, strength: 0.2222222222222222, rc: "Urbanization", lc: "Public & Institutional Investors"},
	{rci: 75, lci: 159, size: 1, strength: 0.0, rc: "Urbanization", lc: "NONE"},
	{rci: 76, lci: 112, size: 1, strength: 0.1111111111111111, rc: "Urbanization", lc: "Media, Entertainment & Information"},
	{rci: 77, lci: 265, size: 4, strength: 0.4444444444444444, rc: "Urbanization", lc: "Real Estate"},
	{rci: 78, lci: 85, size: 1, strength: 0.2, rc: "Human Rights", lc: "Consumer"},
	{rci: 79, lci: 55, size: 1, strength: 0.2, rc: "Human Rights", lc: "Health"},
	{rci: 80, lci: 180, size: 1, strength: 0.2, rc: "Human Rights", lc: "Public & Institutional Investors"},
	{rci: 81, lci: 158, size: 1, strength: 0.0, rc: "Human Rights", lc: "NONE"},
	{rci: 82, lci: 226, size: 1, strength: 0.2, rc: "Human Rights", lc: "Telecom"},
	{rci: 83, lci: 15, size: 5, strength: 0.5555555555555556, rc: "Poverty & Economic Development", lc: "Banking & Capital Markets"},
	{rci: 84, lci: 174, size: 1, strength: 0.1111111111111111, rc: "Poverty & Economic Development", lc: "Public & Institutional Investors"},
	{rci: 85, lci: 154, size: 1, strength: 0.0, rc: "Poverty & Economic Development", lc: "NONE"},
	{rci: 86, lci: 212, size: 1, strength: 0.1111111111111111, rc: "Poverty & Economic Development", lc: "Mining & Metals"},
	{rci: 87, lci: 133, size: 1, strength: 0.1111111111111111, rc: "Poverty & Economic Development", lc: "Renewable Energy"},
	{rci: 88, lci: 268, size: 1, strength: 0.2, rc: "Skills & Talent Mobility", lc: "unknown"},
	{rci: 89, lci: 173, size: 1, strength: 0.2, rc: "Skills & Talent Mobility", lc: "Public & Institutional Investors"},
	{rci: 90, lci: 153, size: 1, strength: 0.0, rc: "Skills & Talent Mobility", lc: "NONE"},
	{rci: 91, lci: 106, size: 1, strength: 0.2, rc: "Skills & Talent Mobility", lc: "Media, Entertainment & Information"},
	{rci: 92, lci: 238, size: 1, strength: 0.2, rc: "Skills & Talent Mobility", lc: "Aviation, Travel & Tourism"},
	{rci: 93, lci: 12, size: 1, strength: 0.14285714285714285, rc: "India", lc: "Banking & Capital Markets"},
	{rci: 94, lci: 46, size: 1, strength: 0.14285714285714285, rc: "India", lc: "Health"},
	{rci: 95, lci: 172, size: 3, strength: 0.42857142857142855, rc: "India", lc: "Public & Institutional Investors"},
	{rci: 96, lci: 255, size: 1, strength: 0.14285714285714285, rc: "India", lc: "Automotive"},
	{rci: 97, lci: 151, size: 1, strength: 0.0, rc: "India", lc: "NONE"},
	{rci: 98, lci: 195, size: 3, strength: 0.375, rc: "Ocean Governance", lc: "Logistics & Supply Chain"},
	{rci: 99, lci: 150, size: 1, strength: 0.0, rc: "Ocean Governance", lc: "NONE"},
	{rci: 100, lci: 211, size: 1, strength: 0.125, rc: "Ocean Governance", lc: "Mining & Metals"},
	{rci: 101, lci: 126, size: 1, strength: 0.125, rc: "Ocean Governance", lc: "Renewable Energy"},
	{rci: 102, lci: 104, size: 2, strength: 0.25, rc: "Ocean Governance", lc: "Media, Entertainment & Information"},
	{rci: 103, lci: 171, size: 2, strength: 0.25, rc: "Future of Government", lc: "Public & Institutional Investors"},
	{rci: 104, lci: 254, size: 1, strength: 0.125, rc: "Future of Government", lc: "Automotive"},
	{rci: 105, lci: 125, size: 1, strength: 0.125, rc: "Future of Government", lc: "Renewable Energy"},
	{rci: 106, lci: 103, size: 3, strength: 0.375, rc: "Future of Government", lc: "Media, Entertainment & Information"},
	{rci: 107, lci: 223, size: 1, strength: 0.125, rc: "Future of Government", lc: "Telecom"},
	{rci: 108, lci: 229, size: 1, strength: 0.2, rc: "Africa", lc: "Telecom"},
	{rci: 109, lci: 30, size: 2, strength: 0.4, rc: "Africa", lc: "Banking & Capital Markets"},
	{rci: 110, lci: 61, size: 1, strength: 0.2, rc: "Africa", lc: "Health"},
	{rci: 111, lci: 116, size: 1, strength: 0.2, rc: "Africa", lc: "Media, Entertainment & Information"},
	{rci: 112, lci: 182, size: 1, strength: 0.125, rc: "Aviation, Travel & Tourism", lc: "Public & Institutional Investors"},
	{rci: 113, lci: 88, size: 5, strength: 0.625, rc: "Aviation, Travel & Tourism", lc: "Consumer"},
	{rci: 114, lci: 141, size: 1, strength: 0.125, rc: "Aviation, Travel & Tourism", lc: "Renewable Energy"},
	{rci: 115, lci: 200, size: 1, strength: 0.125, rc: "Aviation, Travel & Tourism", lc: "Logistics & Supply Chain"},
	{rci: 116, lci: 227, size: 2, strength: 0.2857142857142857, rc: "Education", lc: "Telecom"},
	{rci: 117, lci: 57, size: 3, strength: 0.42857142857142855, rc: "Education", lc: "Health"},
	{rci: 118, lci: 86, size: 1, strength: 0.14285714285714285, rc: "Education", lc: "Consumer"},
	{rci: 119, lci: 113, size: 1, strength: 0.14285714285714285, rc: "Education", lc: "Media, Entertainment & Information"},
	{rci: 120, lci: 27, size: 3, strength: 0.5, rc: "Geopolitical Risk", lc: "Banking & Capital Markets"},
	{rci: 121, lci: 139, size: 1, strength: 0.16666666666666666, rc: "Geopolitical Risk", lc: "Renewable Energy"},
	{rci: 122, lci: 262, size: 1, strength: 0.16666666666666666, rc: "Geopolitical Risk", lc: "Private Fund Managers"},
	{rci: 123, lci: 199, size: 1, strength: 0.16666666666666666, rc: "Geopolitical Risk", lc: "Logistics & Supply Chain"},
	{rci: 124, lci: 241, size: 4, strength: 0.5, rc: "Terrorism", lc: "Aviation, Travel & Tourism"},
	{rci: 125, lci: 53, size: 2, strength: 0.25, rc: "Terrorism", lc: "Health"},
	{rci: 126, lci: 110, size: 1, strength: 0.125, rc: "Terrorism", lc: "Media, Entertainment & Information"},
	{rci: 127, lci: 156, size: 1, strength: 0.0, rc: "Terrorism", lc: "NONE"},
	{rci: 128, lci: 179, size: 2, strength: 0.2222222222222222, rc: "Catastrophic Risks", lc: "Public & Institutional Investors"},
	{rci: 129, lci: 24, size: 3, strength: 0.3333333333333333, rc: "Catastrophic Risks", lc: "Banking & Capital Markets"},
	{rci: 130, lci: 250, size: 2, strength: 0.2222222222222222, rc: "Catastrophic Risks", lc: "Insurance & Asset Management"},
	{rci: 131, lci: 198, size: 2, strength: 0.2222222222222222, rc: "Catastrophic Risks", lc: "Logistics & Supply Chain"},
	{rci: 132, lci: 52, size: 3, strength: 0.5, rc: "Intellectual Property System", lc: "Health"},
	{rci: 133, lci: 83, size: 1, strength: 0.16666666666666666, rc: "Intellectual Property System", lc: "Consumer"},
	{rci: 134, lci: 109, size: 1, strength: 0.16666666666666666, rc: "Intellectual Property System", lc: "Media, Entertainment & Information"},
	{rci: 135, lci: 197, size: 1, strength: 0.16666666666666666, rc: "Intellectual Property System", lc: "Logistics & Supply Chain"},
	{rci: 136, lci: 240, size: 1, strength: 0.07692307692307693, rc: "Media, Entertainment & Information", lc: "Aviation, Travel & Tourism"},
	{rci: 137, lci: 224, size: 8, strength: 0.6153846153846154, rc: "Media, Entertainment & Information", lc: "Telecom"},
	{rci: 138, lci: 81, size: 3, strength: 0.23076923076923078, rc: "Media, Entertainment & Information", lc: "Consumer"},
	{rci: 139, lci: 108, size: 1, strength: 0.07692307692307693, rc: "Media, Entertainment & Information", lc: "Media, Entertainment & Information"},
	{rci: 140, lci: 258, size: 1, strength: 0.2, rc: "Mining & Metals", lc: "Automotive"},
	{rci: 141, lci: 176, size: 2, strength: 0.4, rc: "Mining & Metals", lc: "Public & Institutional Investors"},
	{rci: 142, lci: 18, size: 1, strength: 0.2, rc: "Mining & Metals", lc: "Banking & Capital Markets"},
	{rci: 143, lci: 263, size: 1, strength: 0.2, rc: "Mining & Metals", lc: "Private Fund Managers"},
	{rci: 144, lci: 47, size: 7, strength: 0.7, rc: "Ageing", lc: "Health"},
	{rci: 145, lci: 78, size: 1, strength: 0.1, rc: "Ageing", lc: "Consumer"},
	{rci: 146, lci: 247, size: 1, strength: 0.1, rc: "Ageing", lc: "Insurance & Asset Management"},
	{rci: 147, lci: 105, size: 1, strength: 0.1, rc: "Ageing", lc: "Media, Entertainment & Information"},
	{rci: 148, lci: 256, size: 1, strength: 0.14285714285714285, rc: "Climate Change", lc: "Automotive"},
	{rci: 149, lci: 236, size: 3, strength: 0.42857142857142855, rc: "Climate Change", lc: "Aviation, Travel & Tourism"},
	{rci: 150, lci: 130, size: 2, strength: 0.2857142857142857, rc: "Climate Change", lc: "Renewable Energy"},
	{rci: 151, lci: 264, size: 1, strength: 0.14285714285714285, rc: "Climate Change", lc: "Private Fund Managers"},
	{rci: 152, lci: 13, size: 1, strength: 0.14285714285714285, rc: "Korea", lc: "Banking & Capital Markets"},
	{rci: 153, lci: 76, size: 1, strength: 0.14285714285714285, rc: "Korea", lc: "Consumer"},
	{rci: 154, lci: 267, size: 1, strength: 0.14285714285714285, rc: "Korea", lc: "Real Estate"},
	{rci: 155, lci: 129, size: 4, strength: 0.5714285714285714, rc: "Korea", lc: "Renewable Energy"},
	{rci: 156, lci: 75, size: 2, strength: 0.3333333333333333, rc: "Automotive", lc: "Consumer"},
	{rci: 157, lci: 246, size: 1, strength: 0.16666666666666666, rc: "Automotive", lc: "Insurance & Asset Management"},
	{rci: 158, lci: 128, size: 2, strength: 0.3333333333333333, rc: "Automotive", lc: "Renewable Energy"},
	{rci: 159, lci: 196, size: 1, strength: 0.16666666666666666, rc: "Automotive", lc: "Logistics & Supply Chain"},
	{rci: 160, lci: 45, size: 2, strength: 0.25, rc: "Benchmarking Progress", lc: "Health"},
	{rci: 161, lci: 73, size: 2, strength: 0.25, rc: "Benchmarking Progress", lc: "Consumer"},
	{rci: 162, lci: 101, size: 3, strength: 0.375, rc: "Benchmarking Progress", lc: "Media, Entertainment & Information"},
	{rci: 163, lci: 149, size: 1, strength: 0.0, rc: "Benchmarking Progress", lc: "NONE"},
	{rci: 164, lci: 44, size: 2, strength: 0.25, rc: "Competitiveness", lc: "Health"},
	{rci: 165, lci: 100, size: 1, strength: 0.125, rc: "Competitiveness", lc: "Media, Entertainment & Information"},
	{rci: 166, lci: 124, size: 3, strength: 0.375, rc: "Competitiveness", lc: "Renewable Energy"},
	{rci: 167, lci: 193, size: 2, strength: 0.25, rc: "Competitiveness", lc: "Logistics & Supply Chain"},
	{rci: 168, lci: 221, size: 1, strength: 0.16666666666666666, rc: "Emerging Multinationals", lc: "Telecom"},
	{rci: 169, lci: 42, size: 1, strength: 0.16666666666666666, rc: "Emerging Multinationals", lc: "Health"},
	{rci: 170, lci: 8, size: 2, strength: 0.3333333333333333, rc: "Emerging Multinationals", lc: "Banking & Capital Markets"},
	{rci: 171, lci: 72, size: 2, strength: 0.3333333333333333, rc: "Emerging Multinationals", lc: "Consumer"},
	{rci: 172, lci: 40, size: 1, strength: 0.125, rc: "Consumer", lc: "Health"},
	{rci: 173, lci: 69, size: 1, strength: 0.125, rc: "Consumer", lc: "Consumer"},
	{rci: 174, lci: 96, size: 3, strength: 0.375, rc: "Consumer", lc: "Media, Entertainment & Information"},
	{rci: 175, lci: 191, size: 3, strength: 0.375, rc: "Consumer", lc: "Logistics & Supply Chain"},
	{rci: 176, lci: 168, size: 2, strength: 0.2857142857142857, rc: "Humanitarian Assistance", lc: "Public & Institutional Investors"},
	{rci: 177, lci: 39, size: 1, strength: 0.14285714285714285, rc: "Humanitarian Assistance", lc: "Health"},
	{rci: 178, lci: 243, size: 1, strength: 0.14285714285714285, rc: "Humanitarian Assistance", lc: "Insurance & Asset Management"},
	{rci: 179, lci: 190, size: 3, strength: 0.42857142857142855, rc: "Humanitarian Assistance", lc: "Logistics & Supply Chain"},
	{rci: 180, lci: 167, size: 3, strength: 0.5, rc: "Employment & Social Protection", lc: "Public & Institutional Investors"},
	{rci: 181, lci: 6, size: 1, strength: 0.16666666666666666, rc: "Employment & Social Protection", lc: "Banking & Capital Markets"},
	{rci: 182, lci: 68, size: 1, strength: 0.16666666666666666, rc: "Employment & Social Protection", lc: "Consumer"},
	{rci: 183, lci: 189, size: 1, strength: 0.16666666666666666, rc: "Employment & Social Protection", lc: "Logistics & Supply Chain"},
	{rci: 184, lci: 233, size: 2, strength: 0.25, rc: "Space Security", lc: "Aviation, Travel & Tourism"},
	{rci: 185, lci: 219, size: 4, strength: 0.5, rc: "Space Security", lc: "Telecom"},
	{rci: 186, lci: 5, size: 1, strength: 0.125, rc: "Space Security", lc: "Banking & Capital Markets"},
	{rci: 187, lci: 95, size: 1, strength: 0.125, rc: "Space Security", lc: "Media, Entertainment & Information"},
	{rci: 188, lci: 232, size: 1, strength: 0.25, rc: "Migration", lc: "Aviation, Travel & Tourism"},
	{rci: 189, lci: 4, size: 1, strength: 0.25, rc: "Migration", lc: "Banking & Capital Markets"},
	{rci: 190, lci: 38, size: 1, strength: 0.25, rc: "Migration", lc: "Health"},
	{rci: 191, lci: 67, size: 1, strength: 0.25, rc: "Migration", lc: "Consumer"},
	{rci: 192, lci: 253, size: 1, strength: 0.14285714285714285, rc: "Trade", lc: "Automotive"},
	{rci: 193, lci: 3, size: 1, strength: 0.14285714285714285, rc: "Trade", lc: "Banking & Capital Markets"},
	{rci: 194, lci: 206, size: 1, strength: 0.14285714285714285, rc: "Trade", lc: "Mining & Metals"},
	{rci: 195, lci: 188, size: 4, strength: 0.5714285714285714, rc: "Trade", lc: "Logistics & Supply Chain"},
	{rci: 196, lci: 252, size: 2, strength: 0.25, rc: "Japan", lc: "Automotive"},
	{rci: 197, lci: 37, size: 2, strength: 0.25, rc: "Japan", lc: "Health"},
	{rci: 198, lci: 66, size: 1, strength: 0.125, rc: "Japan", lc: "Consumer"},
	{rci: 199, lci: 123, size: 3, strength: 0.375, rc: "Japan", lc: "Renewable Energy"},
	{rci: 200, lci: 231, size: 1, strength: 0.2, rc: "Women's Empowerment", lc: "Aviation, Travel & Tourism"},
	{rci: 201, lci: 34, size: 1, strength: 0.2, rc: "Women's Empowerment", lc: "Health"},
	{rci: 202, lci: 93, size: 2, strength: 0.4, rc: "Women's Empowerment", lc: "Media, Entertainment & Information"},
	{rci: 203, lci: 145, size: 1, strength: 0.0, rc: "Women's Empowerment", lc: "NONE"},
	{rci: 204, lci: 186, size: 2, strength: 0.5, rc: "Institutional Governance Systems", lc: "Public & Institutional Investors"},
	{rci: 205, lci: 31, size: 1, strength: 0.25, rc: "Institutional Governance Systems", lc: "Banking & Capital Markets"},
	{rci: 206, lci: 118, size: 1, strength: 0.25, rc: "Institutional Governance Systems", lc: "Media, Entertainment & Information"},
	{rci: 207, lci: 225, size: 1, strength: 0.2, rc: "South-East Asia", lc: "Telecom"},
	{rci: 208, lci: 23, size: 3, strength: 0.6, rc: "South-East Asia", lc: "Banking & Capital Markets"},
	{rci: 209, lci: 84, size: 1, strength: 0.2, rc: "South-East Asia", lc: "Consumer"},
	{rci: 210, lci: 177, size: 1, strength: 0.25, rc: "Insurance & Asset Management", lc: "Public & Institutional Investors"},
	{rci: 211, lci: 21, size: 2, strength: 0.5, rc: "Insurance & Asset Management", lc: "Banking & Capital Markets"},
	{rci: 212, lci: 249, size: 1, strength: 0.25, rc: "Insurance & Asset Management", lc: "Insurance & Asset Management"},
	{rci: 213, lci: 51, size: 1, strength: 0.14285714285714285, rc: "Emerging Technologies", lc: "Health"},
	{rci: 214, lci: 82, size: 1, strength: 0.14285714285714285, rc: "Emerging Technologies", lc: "Consumer"},
	{rci: 215, lci: 137, size: 5, strength: 0.7142857142857143, rc: "Emerging Technologies", lc: "Renewable Energy"},
	{rci: 216, lci: 248, size: 1, strength: 0.25, rc: "Fragile States", lc: "Insurance & Asset Management"},
	{rci: 217, lci: 135, size: 1, strength: 0.25, rc: "Fragile States", lc: "Renewable Energy"},
	{rci: 218, lci: 213, size: 2, strength: 0.5, rc: "Fragile States", lc: "Mining & Metals"},
	{rci: 219, lci: 237, size: 1, strength: 0.14285714285714285, rc: "Logistics & Supply Chain", lc: "Aviation, Travel & Tourism"},
	{rci: 220, lci: 77, size: 3, strength: 0.42857142857142855, rc: "Logistics & Supply Chain", lc: "Consumer"},
	{rci: 221, lci: 132, size: 3, strength: 0.42857142857142855, rc: "Logistics & Supply Chain", lc: "Renewable Energy"},
	{rci: 222, lci: 235, size: 1, strength: 0.25, rc: "Ecosystems & Biodiversity", lc: "Aviation, Travel & Tourism"},
	{rci: 223, lci: 74, size: 2, strength: 0.5, rc: "Ecosystems & Biodiversity", lc: "Consumer"},
	{rci: 224, lci: 127, size: 1, strength: 0.25, rc: "Ecosystems & Biodiversity", lc: "Renewable Energy"},
	{rci: 225, lci: 11, size: 2, strength: 0.3333333333333333, rc: "Middle East & North Africa", lc: "Banking & Capital Markets"},
	{rci: 226, lci: 102, size: 3, strength: 0.5, rc: "Middle East & North Africa", lc: "Media, Entertainment & Information"},
	{rci: 227, lci: 209, size: 1, strength: 0.16666666666666666, rc: "Middle East & North Africa", lc: "Mining & Metals"},
	{rci: 228, lci: 234, size: 2, strength: 0.2857142857142857, rc: "Organized Crime", lc: "Aviation, Travel & Tourism"},
	{rci: 229, lci: 10, size: 4, strength: 0.5714285714285714, rc: "Organized Crime", lc: "Banking & Capital Markets"},
	{rci: 230, lci: 208, size: 1, strength: 0.14285714285714285, rc: "Organized Crime", lc: "Mining & Metals"},
	{rci: 231, lci: 9, size: 3, strength: 0.6, rc: "Public & Institutional Investors", lc: "Banking & Capital Markets"},
	{rci: 232, lci: 245, size: 1, strength: 0.2, rc: "Public & Institutional Investors", lc: "Insurance & Asset Management"},
	{rci: 233, lci: 261, size: 1, strength: 0.2, rc: "Public & Institutional Investors", lc: "Private Fund Managers"},
	{rci: 234, lci: 41, size: 4, strength: 0.4, rc: "Chronic Diseases & Well-being", lc: "Health"},
	{rci: 235, lci: 70, size: 4, strength: 0.4, rc: "Chronic Diseases & Well-being", lc: "Consumer"},
	{rci: 236, lci: 98, size: 2, strength: 0.2, rc: "Chronic Diseases & Well-being", lc: "Media, Entertainment & Information"},
	{rci: 237, lci: 7, size: 4, strength: 0.6666666666666666, rc: "China", lc: "Banking & Capital Markets"},
	{rci: 238, lci: 207, size: 1, strength: 0.16666666666666666, rc: "China", lc: "Mining & Metals"},
	{rci: 239, lci: 147, size: 1, strength: 0.0, rc: "China", lc: "NONE"},
	{rci: 240, lci: 230, size: 3, strength: 0.75, rc: "Internet Security", lc: "Telecom"},
	{rci: 241, lci: 164, size: 1, strength: 0.0, rc: "Internet Security", lc: "NONE"},
	{rci: 242, lci: 185, size: 1, strength: 0.2, rc: "Anti-Corruption", lc: "Public & Institutional Investors"},
	{rci: 243, lci: 217, size: 4, strength: 0.8, rc: "Anti-Corruption", lc: "Mining & Metals"},
	{rci: 244, lci: 178, size: 2, strength: 0.3333333333333333, rc: "Real Estate", lc: "Public & Institutional Investors"},
	{rci: 245, lci: 22, size: 4, strength: 0.6666666666666666, rc: "Real Estate", lc: "Banking & Capital Markets"},
	{rci: 246, lci: 20, size: 3, strength: 0.75, rc: "Fiscal Crises", lc: "Banking & Capital Markets"},
	{rci: 247, lci: 49, size: 1, strength: 0.25, rc: "Fiscal Crises", lc: "Health"},
	{rci: 248, lci: 259, size: 1, strength: 0.5, rc: "Renewable Energy", lc: "Automotive"},
	{rci: 249, lci: 19, size: 1, strength: 0.5, rc: "Renewable Energy", lc: "Banking & Capital Markets"},
	{rci: 250, lci: 257, size: 2, strength: 0.3333333333333333, rc: "Energy Security", lc: "Automotive"},
	{rci: 251, lci: 131, size: 4, strength: 0.6666666666666666, rc: "Energy Security", lc: "Renewable Energy"},
	{rci: 252, lci: 14, size: 5, strength: 0.8333333333333334, rc: "International Monetary System", lc: "Banking & Capital Markets"},
	{rci: 253, lci: 152, size: 1, strength: 0.0, rc: "International Monetary System", lc: "NONE"},
	{rci: 254, lci: 210, size: 1, strength: 0.5, rc: "Latin America", lc: "Mining & Metals"},
	{rci: 255, lci: 194, size: 1, strength: 0.5, rc: "Latin America", lc: "Logistics & Supply Chain"},
	{rci: 256, lci: 71, size: 1, strength: 0.25, rc: "Banking & Capital Markets", lc: "Consumer"},
	{rci: 257, lci: 244, size: 3, strength: 0.75, rc: "Banking & Capital Markets", lc: "Insurance & Asset Management"},
	{rci: 258, lci: 220, size: 1, strength: 0.1, rc: "Informed Societies", lc: "Telecom"},
	{rci: 259, lci: 97, size: 9, strength: 0.9, rc: "Informed Societies", lc: "Media, Entertainment & Information"},
	{rci: 260, lci: 36, size: 9, strength: 0.9, rc: "Population Growth", lc: "Health"},
	{rci: 261, lci: 65, size: 1, strength: 0.1, rc: "Population Growth", lc: "Consumer"},
	{rci: 262, lci: 122, size: 1, strength: 0.5, rc: "Europe & Central Asia", lc: "Renewable Energy"},
	{rci: 263, lci: 187, size: 1, strength: 0.5, rc: "Europe & Central Asia", lc: "Logistics & Supply Chain"},
	{rci: 264, lci: 218, size: 1, strength: 0.25, rc: "North America", lc: "Telecom"},
	{rci: 265, lci: 2, size: 3, strength: 0.75, rc: "North America", lc: "Banking & Capital Markets"},
	{rci: 266, lci: 26, size: 6, strength: 1.0, rc: "Systemic Financial Risk", lc: "Banking & Capital Markets"},
	{rci: 267, lci: 17, size: 1, strength: 1.0, rc: "Private Fund Managers", lc: "Banking & Capital Markets"},
	{rci: 268, lci: 169, size: 2, strength: 1.0, rc: "Role of Business", lc: "Public & Institutional Investors"},
	{rci: 269, lci: 121, size: 1, strength: 1.0, rc: "Conflict Prevention", lc: "Renewable Energy"}
]